"""Build obfuscated thin-client bundles (PyInstaller + encrypted server URL)."""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

from nexusbridgehub.crypto import encrypt_server_url, generate_build_seed, obfuscate_seed


def write_worker_bundle(
    out_dir: Path,
    *,
    server_url: str,
    build_seed: bytes | None = None,
    register_code: str | None = None,
) -> tuple[bytes, str]:
    """
    Generate worker_bundle.py with encrypted WSS URL and optional custom handlers.

    Args:
        out_dir: Output directory for worker_bundle.py
        server_url: WebSocket server URL (will be encrypted)
        build_seed: Encryption seed (random if not provided)
        register_code: Python code that defines register_handlers(bridge) function

    Returns:
        (build_seed, encrypted_url)
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    seed = build_seed or generate_build_seed()
    encrypted = encrypt_server_url(server_url, seed)
    obfuscated = obfuscate_seed(seed)

    # Prepare custom handlers section
    handlers_section = ""
    if register_code:
        handlers_section = f"\n# Custom handlers\n{register_code.strip()}\n"
    else:
        handlers_section = textwrap.dedent("""
            # Default handlers — override with --register-code
            def register_handlers(bridge):
                bridge.register("ping", lambda: {"status": "ok"})
                bridge.register("status", lambda: {
                    "project": bridge.project_id,
                    "user": bridge.user_id,
                })
        """)

    content = (
        '"""Auto-generated by nexusbridgehub build. Do not edit."""\n'
        f"ENCRYPTED_SERVER_URL = {encrypted!r}\n"
        f"OBFUSCATED_BUILD_SEED = {obfuscated!r}\n"
        f"{handlers_section}"
    )

    (out_dir / "worker_bundle.py").write_text(content, encoding="utf-8")
    return seed, encrypted


def _validate_register_code(code: str) -> None:
    """Validate that register code defines register_handlers function."""
    try:
        namespace: dict[str, Any] = {}
        exec(code, namespace)
        if "register_handlers" not in namespace:
            raise ValueError("register_code must define register_handlers(bridge) function")
        if not callable(namespace["register_handlers"]):
            raise ValueError("register_handlers must be callable")
    except SyntaxError as exc:
        raise ValueError(f"Invalid Python syntax in register_code: {exc}") from exc


def build_executable(
    *,
    server_url: str,
    output_dir: Path,
    name: str = "nexusbridgehub-worker",
    onefile: bool = True,
    icon: Path | None = None,
    register_code: str | None = None,
    noconsole: bool = False,
    gui: bool = False,
) -> Path:
    """
    Build a standalone worker executable with PyInstaller.

    Args:
        server_url: WebSocket server URL (encrypted in binary)
        output_dir: Build output directory
        name: Executable name (without extension)
        onefile: Build single-file executable (vs directory bundle)
        icon: Path to .ico (Windows) or .icns (macOS) icon file
        register_code: Python code defining register_handlers(bridge)
        noconsole: Hide console window (Windows/macOS GUI mode)
        gui: Build with GUI (enables noconsole automatically)

    Returns:
        Path to built executable

    Raises:
        SystemExit: If PyInstaller fails or not installed
    """
    pkg_root = Path(__file__).resolve().parent
    bundle_dir = output_dir / "_bundle"
    seed_path = output_dir / "build_seed.bin"

    # Validate custom handlers before building
    if register_code:
        _validate_register_code(register_code)

    # Generate worker_bundle.py with encrypted config
    seed, _ = write_worker_bundle(
        bundle_dir,
        server_url=server_url,
        register_code=register_code,
    )
    seed_path.write_bytes(seed)

    # Choose entry point: GUI or CLI
    if gui:
        shutil.copy(pkg_root / "worker_gui.py", bundle_dir / "worker_gui.py")
        entry_point = bundle_dir / "worker_gui.py"
        noconsole = True  # GUI always hides console
    else:
        shutil.copy(pkg_root / "worker_app.py", bundle_dir / "worker_app.py")
        entry_point = bundle_dir / "worker_app.py"

    # Build PyInstaller command
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--name", name,
        "--distpath", str(output_dir / "dist"),
        "--workpath", str(output_dir / "build"),
        "--specpath", str(output_dir),
        "--clean",
        "--noconfirm",
    ]

    if onefile:
        cmd.append("--onefile")

    if noconsole:
        cmd.append("--noconsole")

    if icon and icon.exists():
        cmd.extend(["--icon", str(icon)])

    # Add version info for Windows (reduces antivirus false positives)
    if sys.platform == "win32":
        version_file = pkg_root / "version_info.txt"
        if version_file.exists():
            cmd.extend(["--version-file", str(version_file)])

    cmd.extend([
        "--hidden-import=nexusbridgehub",
        "--hidden-import=nexusbridgehub.worker_bundle",
        "--collect-all=nexusbridgehub",
        "--paths", str(bundle_dir),
        str(entry_point),
    ])

    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"PyInstaller failed: {exc}") from exc
    except FileNotFoundError as exc:
        raise SystemExit(
            "PyInstaller not found. Install with: pip install nexusbridgehub[builder]"
        ) from exc

    exe_suffix = ".exe" if sys.platform == "win32" else ""
    exe_path = output_dir / "dist" / f"{name}{exe_suffix}"

    if not exe_path.exists():
        raise SystemExit(f"Build failed: {exe_path} not found")

    return exe_path


def main_cli() -> None:
    parser = argparse.ArgumentParser(
        description="Build NexusBridgeHub worker binary for distribution",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
            Examples:
              # Basic CLI build
              nexusbridgehub --server-url wss://bridge.example.com:8765

              # Build with GUI (recommended for end users)
              nexusbridgehub --server-url wss://bridge.example.com:8765 --gui

              # Build with custom handlers
              nexusbridgehub --server-url wss://... --register-code handlers.py --gui

              # Build with icon and custom name
              nexusbridgehub --server-url wss://... --icon app.ico --name myworker --gui

              # Generate encrypted bundle only (no PyInstaller)
              nexusbridgehub --server-url wss://... --bundle-only
        """),
    )
    parser.add_argument(
        "--server-url",
        required=True,
        help="WebSocket server URL (will be encrypted in binary)",
    )
    parser.add_argument(
        "--output-dir",
        default="./dist",
        help="Output directory for built executable (default: ./dist)",
    )
    parser.add_argument(
        "--name",
        default="nexusbridgehub-worker",
        help="Executable name without extension (default: nexusbridgehub-worker)",
    )
    parser.add_argument(
        "--icon",
        type=Path,
        help="Path to icon file (.ico for Windows, .icns for macOS)",
    )
    parser.add_argument(
        "--register-code",
        type=Path,
        help="Python file defining register_handlers(bridge) for custom commands",
    )
    parser.add_argument(
        "--noconsole",
        action="store_true",
        help="Hide console window (Windows/macOS GUI mode)",
    )
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Build with GUI (shows connection status and activity logs)",
    )
    parser.add_argument(
        "--bundle-only",
        action="store_true",
        help="Generate worker_bundle.py only, skip PyInstaller build",
    )
    parser.add_argument(
        "--onedir",
        action="store_true",
        help="Build directory bundle instead of single executable",
    )
    args = parser.parse_args()

    out = Path(args.output_dir)

    # Load custom handlers if provided
    register_code_str = None
    if args.register_code:
        if not args.register_code.exists():
            raise SystemExit(f"Register code file not found: {args.register_code}")
        register_code_str = args.register_code.read_text(encoding="utf-8")
        try:
            _validate_register_code(register_code_str)
        except ValueError as exc:
            raise SystemExit(f"Invalid register code: {exc}") from exc

    # Validate icon file if provided
    if args.icon and not args.icon.exists():
        raise SystemExit(f"Icon file not found: {args.icon}")

    # Bundle-only mode
    if args.bundle_only:
        seed, enc = write_worker_bundle(
            out,
            server_url=args.server_url,
            register_code=register_code_str,
        )
        print(f"[OK] Bundle written to {out / 'worker_bundle.py'}")
        print(f"[OK] Build seed saved to {out / 'build_seed.bin'}")
        print(f"     Encrypted URL length: {len(enc)} bytes")
        print("\nTo build executable, run without --bundle-only")
        return

    # Full build
    build_mode = "GUI" if args.gui else "CLI"
    print(f"Building {args.name} ({build_mode}) for {sys.platform}...")
    print(f"  Server URL: {args.server_url[:30]}...")
    if args.gui:
        print(f"  Mode: GUI with connection status and activity logs")
    if register_code_str:
        print(f"  Custom handlers: {args.register_code}")
    if args.icon:
        print(f"  Icon: {args.icon}")

    exe = build_executable(
        server_url=args.server_url,
        output_dir=out,
        name=args.name,
        onefile=not args.onedir,
        icon=args.icon,
        register_code=register_code_str,
        noconsole=args.noconsole,
        gui=args.gui,
    )

    print(f"\n[OK] Build successful: {exe}")
    print(f"     Size: {exe.stat().st_size / 1024 / 1024:.1f} MB")
    print(f"     Mode: {build_mode}")
    print(f"     Build seed: {out / 'build_seed.bin'}")
    if args.gui:
        print(f"     Features: Connection status, activity logs, transparency mode")
    print("\nDistribute the executable to users -- no Python installation required!")
